// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG0-b7HwL97rucnDY18jp6f2bDiwoyarI',
    appId: '1:467677134812:web:82954fd2652883580e1919',
    messagingSenderId: '467677134812',
    projectId: 'defenshe-app',
    authDomain: 'defenshe-app.firebaseapp.com',
    storageBucket: 'defenshe-app.firebasestorage.app',
    measurementId: 'G-76R39HKSD7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS3xPNaU9vAbOjPq5L5t5qQndawvTkh8E',
    appId: '1:467677134812:android:fbbc1fe2b1adb6180e1919',
    messagingSenderId: '467677134812',
    projectId: 'defenshe-app',
    storageBucket: 'defenshe-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwinjMPQpera1hUZt61PnUhlIa1mqPQ-g',
    appId: '1:467677134812:ios:f49b17581cc2df160e1919',
    messagingSenderId: '467677134812',
    projectId: 'defenshe-app',
    storageBucket: 'defenshe-app.firebasestorage.app',
    iosBundleId: 'com.example.defenshe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwinjMPQpera1hUZt61PnUhlIa1mqPQ-g',
    appId: '1:467677134812:ios:f49b17581cc2df160e1919',
    messagingSenderId: '467677134812',
    projectId: 'defenshe-app',
    storageBucket: 'defenshe-app.firebasestorage.app',
    iosBundleId: 'com.example.defenshe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAG0-b7HwL97rucnDY18jp6f2bDiwoyarI',
    appId: '1:467677134812:web:b5741a9dbb9a43850e1919',
    messagingSenderId: '467677134812',
    projectId: 'defenshe-app',
    authDomain: 'defenshe-app.firebaseapp.com',
    storageBucket: 'defenshe-app.firebasestorage.app',
    measurementId: 'G-0QNVLV35HH',
  );

}